name: DependsOn

on: workflow_dispatch

jobs:
  Job1:
    runs-on: ubuntu-20.04
    steps:
    - name: stepname
      run: echo "Job1"
  
  Job2:
    needs: example_matrix1
    runs-on: ubuntu-20.04
    steps:
    - name: stepname
      run: echo "Job2"

  Job3:
    needs: example_matrix1
    runs-on: ubuntu-20.04
    steps:
    - name: stepname
      run: echo "Job3"
        
  Job4:
    needs: [example_matrix1, example_matrix2, example_matrix3]
    runs-on: ubuntu-20.04
    steps:
    - name: stepname
      run: echo "Job4"