name: Matrix Build
on: push

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        version: [10, 12, 14]
    runs-on: ubuntu-20.04
    steps:
    - name: stepname
      run: |
        echo ${{ matrix.version }}
        echo ${{ matrix.os }}
