name: 'GitHub Workflow Demo'

on:
  push:
    branches:
    - "dev"
    paths:
    - ".github/workflows/*"
    
  pull_request:
    branches-ignore:
    - 'test/exp*'
  
  workflow_dispatch:
    environment:
      description: 'Environment to run tests against'
      type: environment
      required: true 


jobs:
  sayHello:
    runs-on: ubuntu-latest
    
    steps: 
    - name: runscript
      run:  echo "Howdy GitHub Actions"
   
  sayBye:
    runs-on: windows-latest
    
    steps: 
    - run:  echo "Good Bye!!! See you around"
