name: 'GitHub Workflow Demo'

on:
  push:
    branches:
    - "dev"
    paths:
    - ".github/workflows/*"
    
  pull_request:
    branches-ignore:
    - 'test/exp*'
  
  workflow_dispatch:
    environment:
      description: 'Environment to run tests against'
      type: environment
      required: true 

# A comment to make your workflow easy to understand

jobs:
  sayHello:
    runs-on: ubuntu-latest
    
    steps: 
    - name: runscript-to-say-hello
      run:  echo "Howdy GitHub Actions"

    
   
  sayBye:
    runs-on: windows-latest
    
    steps: 
    # Runs a set of commands using the runners shell
    - name: runscript-to-say-good-bye
      run: | 
        echo "Good Bye!!! "
        echo "See you around"
