name: 'Default environment variables'

on:
  push:
    branches:
    - "dev"

jobs:
  mainjob:
    name: 'Show the Default env vars'
    runs-on: ubuntu-latest
    
    steps:
    - name: show-values-of-env-vars
      run: echo "$GITHUB_ACTION"
          
