name: 'Env Vars'

on:
  push:
    branches:
    - "dev"
  pull_request:

env:
  DAY_OF_WEEK: Monday

jobs:
  mainjob:
    name: 'Show the env vars'
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    
    steps:
    - name: show-values-of-env-vars
      run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
      env:
          First_Name: Mona
