# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example
on:
  workflow_dispatch:
  
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: env

  github-actions-environment-variables-windows:
    runs-on: windows-latest
    steps:
      - run: env

  github-actions-environment-variables-macos:
    runs-on: macos-latest
    steps:
      - run: env
