name: 'USE_ENV_Secretes'

on:  push

jobs:
  custom_GITHUB_ENV_vars:
    runs-on: ubuntu-latest 
    environment: production
    steps:
    - run: echo ${{ secrets.secrete_name }}
    - run: echo ${{ secrets.secrete_name2 }}
    - run: echo ${{ secrets.env_level_secrete }}
