on:
  schedule:
  - cron: '0 1 * * *'
  workflow_dispatch:

name: Add-latest-tag-With-timestamp
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: use_later
      run: |
       echo "::set-output name=TAG_NAME::v1.0.0-alpha-$(date +'%Y-%m-%d-%H-%M')"
       echo "::set-output name=RELEASE_NAME::v1.0.0-alpha-$(date +'%Y-%m-%d-%H-%M')"
    
    - name: CreateRelease
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.use_later.outputs.TAG_NAME }}
        release_name: ${{ steps.use_later.outputs.RELEASE_NAME }}



